SET(ARCH_OS $ENV{ARCH_OS})

IF (ARCH_OS STREQUAL arm-linux)
	SET(ARCH ARM)
	SET(OS   LINUX)
	SET(MY_LIBS_PATH    $ENV{MY_PREFIX}/arm-linux)
ENDIF()

IF (ARCH_OS STREQUAL i386-linux)
	SET(ARCH I386)
	SET(OS   LINUX)
	SET(MY_LIBS_PATH    $ENV{MY_PREFIX}/i386-linux)
ENDIF()

ADD_DEFINITIONS(-D${ARCH} -D${OS}_OS)
ADD_DEFINITIONS(-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64)

# adjust the default behaviour of hte FIND_XXX() NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODULE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_INSTALL_PREFIX ${MY_LIBS_PATH} )

SET(CMAKE_C_FLAGS_DEBUG     "$ENV{CFLAGS} -Wno-deprecated-declarations -O0 -Wall -g -ggdb")
SET(CMAKE_C_FLAGS_RELEASE   "$ENV{CFLAGS} -Wno-deprecated-declarations -O2 -Wall")

FUNCTION(ADD_SHARE_LIBRARY name)
	ADD_LIBRARY(${name} SHARED ${ARGN})
	INSTALL(TARGETS ${name} LIBRARY DESTINATION ${MY_LIBS_PATH}/lib)
ENDFUNCTION(ADD_SHARE_LIBRARY name)

FUNCTION(ADD_STATIC_LIBRARY name)
	ADD_LIBRARY(${name} ${ARGN})
	INSTALL(TARGETS ${name} LIBRARY DESTINATION ${MY_LIBS_PATH}/lib)
ENDFUNCTION(ADD_STATIC_LIBRARY name)
