SET(ARCH_OS $ENV{ARCH_OS})

SET(CMAKE_C_COMPILER_FORCED TRUE)
SET(CMAKE_CXX_COMPILER_FORCED TRUE)

IF (ARCH_OS STREQUAL arm-linux)
	SET(TOOLCHAIN_PREFIX arm-linux-gnueabihf-)
ENDIF()

EXECUTE_PROCESS(COMMAND which ${TOOLCHAIN_PREFIX}gcc
	OUTPUT_VARIABLE COMPILER_FULL_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(CMAKE_C_COMPILER   ${COMPILER_FULL_PATH})

EXECUTE_PROCESS(COMMAND which ${TOOLCHAIN_PREFIX}g++
	OUTPUT_VARIABLE COMPILER_FULL_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
SET(CMAKE_CXX_COMPILER   ${COMPILER_FULL_PATH})
